### PR TITLE
Make MeshBVH.closestPointToPoint, closestPointToGeometry return more info

### LINKED ISSUE #318: Consider making ThreeIntersectionUtilities.checkIntersection() configurable
This issue happens to me because I'm making particular things. But it could lead to general errors that have not been detected yet. Also, this is more an issue of Three.js rather than Three-mesh-bvh.

In short, rays are sneaking through adjacent triangles because I'm deliberately pointing the rays to the edge shared between them.

Let me explain: I'm sampling lots (thousands) of points of interest around a mesh. For each point I'm getting the closest point in the mesh surface with ```MeshBVH.closestPointToPoint()```. This works great. Then I shoot a ray from the point of interest to the closest point, just to obtain the UV coordinates. This ray sometimes sneaks through two triangles (depending on numerical errors). It happens when the POI is located in the region between two triangles as in the following image, where the closest point is always on the edge between the two tris:

imagen

Unexpectedly, for some POIs the rays are hitting none of the two triangles. The reason is just as if there was Z-fighting, because I've pointed the ray right to the edge.

So, to solve this issue, I've replaced (in a hacky way) the calls to ```Ray.intersectTriangle()``` in ```ThreeIntersectionUtilities.checkIntersection()``` to call my own ray-triangle intersection function. This function is more intuitive to read, and although is probably not as performant as Three.js's one (but not by much), it has the advantage of having some hysteresis threshold value. The threshold is tiny (10⁻¹² units), but is sufficient to solve the issue completely. I copied this function from elsewhere years ago, and the threshold is there to solve this precise issue when raycasting meshes. Keep in mind this only works with ```MeshBVH.raycastFirst()```, as redundant intersections could be returned for ```MeshBVH.raycast()```

So my question is, could it be made configurable wich final ray-triangle intersection function is used in Three-mesh-bvh?

Here is the ray-intersection function I've adapted:

```javascript
const intersectionThreshold = 1.0E-12;

const temp_edge1 = new Vector3();
const temp_edge2 = new Vector3();
const temp_normal = new Vector3();

const temp_dif0 = new Vector3();
const temp_dif1 = new Vector3();

function intersectRayTriangle( ray, a, b, c, backfaceCulling, target ) {

	// Taken from the engine Nebula 2 device (http://nebuladevice.cubik.org/), which in turn took it from
	// Magic Software (http://www.cs.unc.edu/~eberly)

	temp_edge1.subVectors( b, a );
	temp_edge2.subVectors( c, a );
	temp_normal.crossVectors( temp_edge1, temp_edge2 ).normalize();

	// Compute the triangle plane equation, Dot( normal, X - v0 ) = 0
	// If the angle between ray and plane is small, they are parallel, so return null.
	const denominator = temp_normal.dot( ray.direction );
	if ( backfaceCulling ) {

		if ( denominator >= - intersectionThreshold ) return null;

	}
	else if ( Math.abs( denominator ) < intersectionThreshold ) return null;

	// Compute ray parameter (t) for the intersection. To do this, substitute and clear in the plane equation:
	// Dot( normal, b - v0 ) + t * Dot( normal, m )
	temp_dif0.subVectors( ray.origin, a );
	const t = - temp_normal.dot( temp_dif0 ) / denominator;
	if ( t < intersectionThreshold ) {
		return null;
	}

	// Obtain the difference between intersection point and vertex 0 of triangle
	temp_dif1.copy( ray.direction ).multiplyScalar( t );
	temp_dif1.add( temp_dif0 );

	// Computes whether intersection point lies in the triangle. From equation dif1 = s0 * e0 + s1 * e1, find s0 and s1
	const e00 = temp_edge1.dot( temp_edge1 );
	const e01 = temp_edge1.dot( temp_edge2 );
	const e11 = temp_edge2.dot( temp_edge2 );
	const det = Math.abs( e00 * e11 - e01 * e01 );
	const r0 = temp_edge1.dot( temp_dif1 );
	const r1 = temp_edge2.dot( temp_dif1 );

	const s0 = e11 * r0 - e01 * r1;
	const s1 = e00 * r1 - e01 * r0;

	if ( s0 >= - intersectionThreshold && s1 >= - intersectionThreshold && ( s0 + s1 ) <= det + intersectionThreshold ) {

		// Intersection point lies in the triangle
		return target.addVectors( a, temp_dif1 );

	}

	// Intersection point lies outside the triangle
	return null;

}

```

### PR DESCRIPTION
**Pull request by yomboprime**
fixes #318, #321 

I've made the changes described in the mentioned issues: Target parameters can be Vector3 (as before), or objects (either ```{ }``` or the object from a previous execution). The objects (if not null) are filled with face indices, normal, uv, etc.

For ```closestPointToGeometry``` I've made it return always the info for target1 (```this.geometry```), but target2 (related to otherGeometry) is updated if it is an object. Mixing Vector3 and info object for target1 and target2 is not suported.

Also I've removed the ```distanceToPoint``` and ```distanceToGeometry``` functions of ```MeshBVH```.

The code has become large, let me know if there is something you would remove/modify.

Edit: Forgot to mention I've run the tests and they work fine. But the benchmark seems not to work, it complains about ```performance.now()``` not being defined.

### CODE REVIEW

**Comment by yomboprime** [comment]
I was creating new vectors instead of reusing the target objects ones. I fixed it in the last commit, bloating even more the code :-/

**Comment by yomboprime** [comment]
I think at this point it could be better to make two versions of each function, for performance reasons and readability. What do you think?

File: src/core/MeshBVH.js [hunk 1]
```diff
@@ -943,13 +1084,74 @@ export class MeshBVH {
...
+			target.face.a = a;
+			target.face.b = b;
+			target.face.c = c;
+			target.face.materialIndex = 0;
+			if ( ! target.face.normal ) target.face.normal = new Vector3();
+			Triangle.getNormal( tempV1, tempV2, tempV3, target.face.normal );
+			if ( ! target.uv ) target.uv = new Vector2();
+			target.uv.copy( uv );
+
+			return target;
```
Comment (gkjohnson) [inline src/core/MeshBVH.js:1136]: A lot of this looks like it could be reused between the two cases in `closestPointToGeometry` and this function -- should we make a utility function for constructing this based on a point, geometry, and triangle index? It could go in the [utils/TriangleUtilities.js file](https://github.com/gkjohnson/three-mesh-bvh/blob/master/src/utils/TriangleUtilities.js). The function could modify an existing object if it's passed in or return a new one if there's no object provided.

**Review by gkjohnson — COMMENTED** [review]
This is great! Thank you so much.

> The code has become large, let me know if there is something you would remove/modify.

I've left a couple comments on the `closestPointToGeometry` but I think the big thing is that constructing the "hit" information object could be done in a utility function to cut down on the logic within each function. And the backwards compatibility / deprecation warnings can happen in a wrapped function, though that doesn't seem to be taking up a lot of space in the functions.

> Edit: Forgot to mention I've run the tests and they work fine. But the benchmark seems not to work, it complains about performance.now() not being defined.

Yes `performance.now` was added in node v16 so I switched over to that from Date.now() for more fidelity.

**Comment by yomboprime** [comment]
I've made a mix of your suggestions and another approach.

I've extracted the hit info collection code in a function as you said, but I don't call it from ```closestPointToPoint``` nor ```closestPointToGeometry```. Instead, I've changed the result and target objects of those two Functions to just contain the point, the distance and the triangle index. Then, the caller can use the utility triangle function afterwards. This saves time when the caller doesn't need hit info, and there is no penalty when hit info is needed.

The utility function is ```getTriangleHitPointInfo()```

I've modified the tests. I can also edit the docs if you think this approach is right.

File: src/core/MeshBVH.js [hunk 2]
```diff
@@ -943,13 +964,27 @@ export class MeshBVH {
...
-	}
+		if ( target ) {
+
+			if ( ! target.point ) target.point = temp1.clone();
+			else target.point.copy( temp1 );
+			target.distance = closestDistance,
+			target.faceIndex = closestDistanceTriIndex;
+			return target;
+
+		} else {
```
Comment (gkjohnson) [inline src/core/MeshBVH.js:977]: I think it's okay to default `target` to an empty object in the constructor which will simplify final condition block further, as well. Then we won't have to handle the "else" condition because it would be guaranteed that the target object is defined.

We can do the same for `closestPointToGeometry` for at least `target1`.

File: src/core/MeshBVH.js [hunk 3]
```diff
@@ -787,19 +789,21 @@ export class MeshBVH {
 										const dist = triangle.distanceToTriangle( triangle2, tempTarget1, tempTarget2 );
 										if ( dist < closestDistance ) {
 
-											if ( target1 ) {
+											if ( tempTargetDest1 ) {
```
Comment (gkjohnson) [inline src/core/MeshBVH.js:792]: `tempTargetDest1` will always be defined, now.

**Review by gkjohnson — COMMENTED** [review]
> I've made a mix of your suggestions and another approach.
> ...
> The utility function is `getTriangleHitPointInfo()`

Interesting! I kinda like the idea. I think in practice calling that function won't be adding a lot of overhead compared to the bounds traversal but lets go with this. Let's just make sure we point to the function from `closestPointToGeometry` and `closestPointToPoint`. If it winds up posing a problem we can always change it easily later.

>  I can also edit the docs if you think this approach is right.

Updating the docs would be great. And lets also make sure the function is exposed  through `index.js` so it's public.

That aside I added a couple more comments. Thanks for the changes so far! I think these should be the last adjustments.

File: src/core/MeshBVH.js [hunk 4]
```diff
@@ -875,13 +881,31 @@ export class MeshBVH {
...
 		trianglePool.releasePrimitive( triangle2 );
 
-		return closestDistance;
+		if ( target2 ) {
 
-	}
+			if ( ! target2.point ) target2.point = tempTargetDest2.clone();
+			else target2.point.copy( tempTargetDest2 );
+			target2.distance = closestDistance,
+			target2.faceIndex = closestDistanceOtherTriIndex;
```
[the remark this answers is not in the document]
Comment (yomboprime) [reply src/core/MeshBVH.js:889]: Yes, I think ```target2.point``` should be converted to the other geometry frame. But the distance should remain the same, no need to recompute it?
Sorry for not spotting the frame issue.

**Comment by yomboprime** [comment]
> Interesting! I kinda like the idea. I think in practice calling that function won't be adding a lot of overhead compared to the bounds traversal but lets go with this. Let's just make sure we point to the function from `closestPointToGeometry` and `closestPointToPoint`. If it winds up posing a problem we can always change it easily later.
> 

Sorry, I don't understand here. What do you mean by 'pointing'? A comment in the code or in the docs?

> Updating the docs would be great. And lets also make sure the function is exposed through `index.js` so it's public.
> 

Sorry, I didn't know exposing in ```index.js``` was neccesary. I will do it.

File: src/core/MeshBVH.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (gkjohnson) [reply src/core/MeshBVH.js:889]: > But the distance should remain the same, no need to recompute it?

If the geometries are scaled differently to one another then the distance represented in each local frame would be different. Ie if "otherGeometry" were scaled to `0.1` while the current geometry were scaled to `10` then there's a scale difference of 100 between them meaning the distance would be different a factor of 100.

Not all transforms will have uniforms scales, though. It would probably be easiest to transform both points into the second geometry in order to recompute the distance.

> Sorry for not spotting the frame issue.

Ha I've been working on this project for awhile now and there are still things I'm surprised I didn't see previously!

**Comment by gkjohnson** [comment]
> Sorry, I don't understand here. What do you mean by 'pointing'? A comment in the code or in the docs?

I just mean a link in the docs from each functions description so users know they can use this new function to compute the remaining hit information.

**Comment by yomboprime** [comment]
Done!

The only issue I've found is: I had to set targets to ```undefined``` so they get the default objects. With ```null``` they stay null.

**Comment by yomboprime** [comment]
Should be done now. I also updated the docs.

File: benchmark/run-benchmark.js [hunk 5]
```diff
@@ -18,8 +18,8 @@ box.min.set( 1, 1, 1 );
 const intersectGeometry = new THREE.TorusBufferGeometry( 5, 5, 100, 50 );
 const geomMat = new THREE.Matrix4().compose( new THREE.Vector3(), new THREE.Quaternion(), new THREE.Vector3( 0.1, 0.1, 0.1 ) );
 
-const target1 = new THREE.Vector3();
-const target2 = new THREE.Vector3();
+const target1 = undefined;
+const target2 = undefined;
```
Comment (gkjohnson) [inline benchmark/run-benchmark.js:22]: Lets set these to empty objects {} so the objects will be reused and to reduce the impact of garbage collection on the benchmark.

File: README.md [hunk 6]
```diff
@@ -499,6 +488,41 @@ getBoundingBox( target : Box3 ) : Box3
...
+		materialIndex: Number,
+		normal: Vector3
+	},
+	uv: Vector2
+}
+```
+
+- `point`: The same point
+- `a`, `b`, `c`: Triangle indices
+- `materialIndex`: Face material index or 0 if not available.
```
Comment (gkjohnson) [inline README.md:520]: From the function implementation it looks like the materialIndex is always set to 0, right? Technically the material index should be based on the `geometry.groups` list, but a better approach will require changes to the "shapecast" function so the current group id is passed down to the callbacks, which I'll make an issue for.

**Review by gkjohnson — COMMENTED** [review]
One more thing! (and a last lint issue to fix) After these we can merge it.

Also sorry for the delay on the workflow results. It's requiring that I approve to run the tests on the PR since it's your first contribution.

File: README.md (hunk 6 above)
Comment (gkjohnson) [reply README.md:520]: #325

**Comment by yomboprime** [comment]
Sorry, I forgot to push the last commit. It should be all done now.

**Comment by gkjohnson** [comment]
This is great, thank you again!
