### PR TITLE
Fix created index array, visualizer

### LINKED ISSUE #75: Make the MeshBVHVisualizer respect multiple roots
#66 introduced multiple roots to accommodate groups. The bvh visualizer should be updated to display all.

### LINKED ISSUE #94: Possible bug in _ensureIndex( )
In a BufferGeometry the index array is an array that specifies a list of vertex-indices with either Uint16 or Uint32 arrays

Here:
`const index = new ( triCount > 65535 ? Uint32Array : Uint16Array )( indexCount );`

You're looking for a triangle count > 65535 to switch to Uint32 arrays whereas I believe that the correct value to check would be the number of vertices, not triangles

e.g.:  assume you have 70000 vertices in a mesh, now you need to push the vertex index 70000 inside the index array -- you can't! since the triangle count is fixed at a third of that value and a Uint16 array was used instead

Checking for vertex count instead of triangles count solved the bug I was having

### PR DESCRIPTION
**Pull request by gkjohnson**
Fix #75
Fix #94
Related to #93 

- Add a test to verify that the correct array type is used for the index buffer
- Fix case where the index buffer would be instantiated with the wrong type
- Make the MeshBVHVisualizer work with multiple BVH roots

### CODE REVIEW

File: src/MeshBVH.js [hunk 1]
```diff
@@ -43,9 +43,9 @@ export default class MeshBVH {
 
 		if ( ! geo.index ) {
 
-			const triCount = geo.attributes.position.count / 3;
-			const indexCount = triCount * 3;
-			const index = new ( triCount > 65535 ? Uint32Array : Uint16Array )( indexCount );
+			const vertexCount = geo.attributes.position.count;
+			const indexCount = vertexCount;
+			const index = new ( vertexCount > 65535 ? Uint32Array : Uint16Array )( indexCount );
```
Comment (mqp) [inline src/MeshBVH.js]: Seems like `indexCount` might as well be eliminated.

**Comment by gkjohnson** [comment]
Ha no worries I had to look at it for a few moments myself to make sure I was thinking about it right.
